postgresql:
    image: postgres:9.4
    environment:
        POSTGRES_USER: resolwe-server
        POSTGRES_DB: resolwe-server
    ports:
        - "55432:5432"
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    environment:
        - discovery.type=single-node
        # Limit JVM's heap memory.
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
        # Disable X-Pack included in the official images.
        - xpack.graph.enabled=false
        - xpack.ml.enabled=false
        - xpack.monitoring.enabled=false
        # NOTE: Elasticsearch complains about unknown setting even though it is
        # documented at:
        # https://www.elastic.co/guide/en/x-pack/5.6/installing-xpack.html#xpack-enabling
        # - xpack.reporting.enabled=false
        - xpack.security.enabled=false
        - xpack.watcher.enabled=false
    ports:
        - "59200:9200"
redis:
    image: redis:3.2
    ports:
        - "56379:6379"
